apiVersion: v2
type: application
name: opentelemetry-demo
version: 0.19.10
description: opentelemetry demo helm chart
home: https://opentelemetry.io/
sources:
  - https://github.com/akkbng/opentelemetry-astronomy-shop
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: "1.3.1"
dependencies:
  - name: opentelemetry-collector
    version: 0.49.4
    repository: file://../opentelemetry-collector
    condition: observability.otelcol.enabled
  - name: jaeger
    version: 0.69.1
    repository: https://jaegertracing.github.io/helm-charts
    condition: observability.jaeger.enabled
  - name: prometheus
    version: 19.7.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: observability.prometheus.enabled
  - name: grafana
    version: 6.52.5
    repository: https://grafana.github.io/helm-charts
    condition: observability.grafana.enabled
