apiVersion: v2
type: application
name: opentelemetry-demo
version: 0.22.3
description: opentelemetry demo helm chart
home: https://opentelemetry.io/
sources:
  - https://github.com/akkbng/opentelemetry-astronomy-shop
appVersion: "1.4.0"
dependencies:
  - name: opentelemetry-collector
    version: 0.56.0
    repository: file://../opentelemetry-collector
    condition: observability.otelcol.enabled
  - name: jaeger
    version: 0.69.1
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
  - name: prometheus
    version: 20.2.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.52.8
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: tempo
    version: 1.3.1
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled
