{
 "title": "Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cpu",
   "type": "gauge",
   "description": "otelcol_process_cpu_seconds",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(otelcol_process_cpu_seconds[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Rss\navg(otelcol_process_memory_rss{}) by (instance)",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otelcol_process_memory_rss{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes of memory obtained from the OS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(otelcol_process_runtime_total_sys_memory_bytes[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trace Sampling Ratio",
   "type": "gauge",
   "description": "avg(rate(otelcol_processor_transparency_count_traces_sampled{sampled=\"true\"}[$__range])) / avg(rate(otelcol_processor_transparency_count_traces_sampled{sampled=\"false\"}[$__range]))",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(otelcol_processor_transparency_count_traces_sampled{sampled=\"true\"}[$__range])) / avg(rate(otelcol_processor_transparency_count_traces_sampled{sampled=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sampling Decision",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(otelcol_processor_transparency_count_traces_sampled[$__range])",
     "legendFormat": "Sampled {{sampled}}"
    }
   ]
  },
  {
   "title": "Sampling Decision Latency Sum",
   "type": "stat",
   "description": "Sum of Latency (in microseconds) of a given sampling policy",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(otelcol_processor_transparency_sampling_decision_latency_sum{service_name=\"otel-transparency-collector\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Span Export Ratio",
   "type": "gauge",
   "description": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans{}[$__range])))) ",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans{}[$__range])))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sent Spans",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_spans{exporter=\"otlp\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}